[scenario]
name = "drill_2_2_dodge_45784"
seed = 45784
hero_count = 1
enemy_count = 0
max_ticks = 300
room_type = "Entry"
hero_templates = [
    "scout",
]
enemy_hero_templates = []
drill_type = "dodge_zones"
target_position = [
    18.0,
    18.0,
]
action_mask = "move_only"

[[scenario.hazards]]
hazard_type = "damage_zone"
position = [
    12.1,
    13.0,
]
radius = 3.0
damage_per_tick = 5.0
team = "neutral"

[[scenario.hazards]]
hazard_type = "damage_zone"
position = [
    7.7,
    12.9,
]
radius = 2.3
damage_per_tick = 5.0
team = "neutral"

[[scenario.hazards]]
hazard_type = "damage_zone"
position = [
    6.3,
    11.4,
]
radius = 2.4
damage_per_tick = 5.0
team = "neutral"

[[scenario.hazards]]
hazard_type = "damage_zone"
position = [
    5.9,
    7.2,
]
radius = 2.7
damage_per_tick = 5.0
team = "neutral"

[[scenario.hazards]]
hazard_type = "damage_zone"
position = [
    11.5,
    13.2,
]
radius = 2.9
damage_per_tick = 5.0
team = "neutral"

[[scenario.hazards]]
hazard_type = "damage_zone"
position = [
    13.7,
    7.4,
]
radius = 2.3
damage_per_tick = 5.0
team = "neutral"

[scenario.objective]
objective_type = "reach_position"
position = [
    18.0,
    18.0,
]
radius = 1.0
