#!/usr/bin/env python3
"""PPO training for ability transformer actor-critic.

Loads episodes generated by `xtask scenario oracle transformer-rl generate`,
computes GAE advantages, and trains with clipped PPO.

Usage:
    uv run --with numpy --with torch training/train_rl.py \
        generated/rl_episodes.jsonl \
        --pretrained generated/ability_transformer_decision_v2.pt \
        --entity-encoder generated/entity_encoder_pretrained_v3.pt \
        -o generated/actor_critic.pt \
        --iterations 50
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

sys.path.insert(0, str(Path(__file__).resolve().parent))
from model import (
    AbilityActorCritic,
    AbilityTransformerDecision,
    NUM_ACTIONS,
    MAX_ABILITIES,
)
from tokenizer import AbilityTokenizer
from grokfast import GrokfastEMA

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------


def load_episodes(path: Path) -> list[dict]:
    episodes = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line:
                episodes.append(json.loads(line))
    return episodes


def flatten_steps(episodes: list[dict]) -> tuple[list[dict], list[int]]:
    """Flatten episodes into individual steps with episode indices."""
    steps = []
    ep_indices = []
    for ei, ep in enumerate(episodes):
        for step in ep["steps"]:
            step["_episode_reward"] = ep["reward"]
            steps.append(step)
            ep_indices.append(ei)
    return steps, ep_indices


# ---------------------------------------------------------------------------
# GAE computation
# ---------------------------------------------------------------------------


def compute_gae(
    episodes: list[dict],
    value_fn,
    tokenizer: AbilityTokenizer,
    gamma: float = 0.99,
    lam: float = 0.95,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Compute GAE advantages and returns for all steps.

    Returns (advantages, returns, old_values) as flat arrays.
    """
    all_advantages = []
    all_returns = []
    all_values = []

    for ep in episodes:
        steps = ep["steps"]
        if not steps:
            continue

        # Get value predictions for all states in this episode
        game_states = torch.tensor(
            [s["game_state"] for s in steps], dtype=torch.float32, device=DEVICE
        )
        with torch.no_grad():
            values = value_fn(game_states).squeeze(-1).cpu().numpy()

        # Terminal value
        terminal_value = 0.0  # episode is done

        # Compute GAE backwards
        n = len(steps)
        advantages = np.zeros(n, dtype=np.float32)
        gae = 0.0

        for t in reversed(range(n)):
            reward = steps[t]["step_reward"]
            # Add terminal reward to last step
            if t == n - 1:
                reward += ep["reward"]
                next_value = terminal_value
            else:
                next_value = values[t + 1]

            delta = reward + gamma * next_value - values[t]
            gae = delta + gamma * lam * gae
            advantages[t] = gae

        returns = advantages + values

        all_advantages.extend(advantages)
        all_returns.extend(returns)
        all_values.extend(values)

    return (
        np.array(all_advantages, dtype=np.float32),
        np.array(all_returns, dtype=np.float32),
        np.array(all_values, dtype=np.float32),
    )


# ---------------------------------------------------------------------------
# PPO update
# ---------------------------------------------------------------------------


def ppo_update(
    model: AbilityActorCritic,
    optimizer: torch.optim.Optimizer,
    grokfast: GrokfastEMA | None,
    steps: list[dict],
    advantages: np.ndarray,
    returns: np.ndarray,
    episodes: list[dict],
    tokenizer: AbilityTokenizer,
    clip_eps: float = 0.2,
    value_coeff: float = 0.5,
    entropy_coeff: float = 0.01,
    ppo_epochs: int = 4,
    batch_size: int = 256,
    max_grad_norm: float = 0.5,
) -> dict:
    """Run PPO update epochs on collected data."""
    n = len(steps)
    if n == 0:
        return {}

    # Prepare tensors
    game_states = torch.tensor(
        [s["game_state"] for s in steps], dtype=torch.float32, device=DEVICE
    )
    actions = torch.tensor([s["action"] for s in steps], dtype=torch.long, device=DEVICE)
    old_log_probs = torch.tensor(
        [s["log_prob"] for s in steps], dtype=torch.float32, device=DEVICE
    )
    masks = torch.tensor([s["mask"] for s in steps], dtype=torch.bool, device=DEVICE)
    adv_tensor = torch.tensor(advantages, dtype=torch.float32, device=DEVICE)
    ret_tensor = torch.tensor(returns, dtype=torch.float32, device=DEVICE)

    # Normalize advantages
    adv_tensor = (adv_tensor - adv_tensor.mean()) / (adv_tensor.std() + 1e-8)

    # Pre-compute ability CLS embeddings for each step
    # Build unit_id → ability tokens mapping from episodes
    unit_ability_tokens: dict[int, list[list[int]]] = {}
    for ep in episodes:
        for uid_str, tokens_list in ep.get("unit_abilities", {}).items():
            uid = int(uid_str)
            if uid not in unit_ability_tokens:
                unit_ability_tokens[uid] = tokens_list

    # For each step, we need the ability CLS embeddings
    # Cache CLS per (unit_id, ability_idx)
    cls_cache: dict[tuple[int, int], torch.Tensor] = {}

    model.train()
    for uid, tokens_list in unit_ability_tokens.items():
        for aidx, tokens in enumerate(tokens_list):
            ids = torch.tensor([tokens], dtype=torch.long, device=DEVICE)
            amask = (ids != 0).float()
            with torch.no_grad():
                cls_emb = model.transformer.cls_embedding(ids, amask)
            cls_cache[(uid, aidx)] = cls_emb.squeeze(0)  # (d_model,)

    metrics = {
        "policy_loss": 0.0,
        "value_loss": 0.0,
        "entropy": 0.0,
        "approx_kl": 0.0,
        "clip_frac": 0.0,
        "n_updates": 0,
    }

    for epoch in range(ppo_epochs):
        indices = np.random.permutation(n)

        for start in range(0, n, batch_size):
            end = min(start + batch_size, n)
            idx = indices[start:end]
            B = len(idx)

            batch_gs = game_states[idx]
            batch_actions = actions[idx]
            batch_old_lp = old_log_probs[idx]
            batch_masks = masks[idx]
            batch_adv = adv_tensor[idx]
            batch_ret = ret_tensor[idx]

            # Build ability CLS for this batch
            ability_cls: list[torch.Tensor | None] = [None] * MAX_ABILITIES
            # For simplicity in first iteration: we pass None for abilities
            # and let the model use -inf for ability logits.
            # The base actions (attack/move/hold) are what we're primarily training.
            #
            # To properly handle abilities, we'd need per-step unit_id lookups.
            # For now, build per-step ability CLS:
            per_step_cls = []
            for ii in idx:
                step = steps[ii]
                uid = step["unit_id"]
                slot_cls = []
                if uid in unit_ability_tokens:
                    for aidx in range(MAX_ABILITIES):
                        key = (uid, aidx)
                        if key in cls_cache:
                            slot_cls.append(cls_cache[key])
                        else:
                            slot_cls.append(None)
                else:
                    slot_cls = [None] * MAX_ABILITIES
                per_step_cls.append(slot_cls)

            # Stack ability CLS into batch tensors
            ability_cls_batch: list[torch.Tensor | None] = [None] * MAX_ABILITIES
            for aidx in range(MAX_ABILITIES):
                valid = []
                valid_indices = []
                for bi, step_cls in enumerate(per_step_cls):
                    if step_cls[aidx] is not None:
                        valid.append(step_cls[aidx])
                        valid_indices.append(bi)

                if valid:
                    stacked = torch.stack(valid)  # (n_valid, d_model)
                    # Expand to full batch with zeros for missing
                    full = torch.zeros(B, model.d_model, device=DEVICE)
                    for vi, bi in enumerate(valid_indices):
                        full[bi] = stacked[vi]
                    ability_cls_batch[aidx] = full

            # Forward pass
            logits, values = model(batch_gs, ability_cls_batch)
            values = values.squeeze(-1)

            # Mask logits
            logits = logits.masked_fill(~batch_masks, -1e9)

            # Log probs
            log_probs = F.log_softmax(logits, dim=-1)
            action_log_probs = log_probs.gather(1, batch_actions.unsqueeze(1)).squeeze(1)

            # Entropy
            probs = F.softmax(logits, dim=-1)
            entropy = -(probs * log_probs).sum(-1).mean()

            # PPO ratio
            ratio = (action_log_probs - batch_old_lp).exp()

            # Clipped surrogate
            surr1 = ratio * batch_adv
            surr2 = ratio.clamp(1 - clip_eps, 1 + clip_eps) * batch_adv
            policy_loss = -torch.min(surr1, surr2).mean()

            # Value loss
            value_loss = F.mse_loss(values, batch_ret)

            # Total loss
            loss = policy_loss + value_coeff * value_loss - entropy_coeff * entropy

            optimizer.zero_grad()
            loss.backward()

            if grokfast is not None:
                grokfast.step()

            nn.utils.clip_grad_norm_(model.parameters(), max_grad_norm)
            optimizer.step()

            # Track metrics
            with torch.no_grad():
                approx_kl = (batch_old_lp - action_log_probs).mean().item()
                clip_frac = ((ratio - 1).abs() > clip_eps).float().mean().item()

            metrics["policy_loss"] += policy_loss.item()
            metrics["value_loss"] += value_loss.item()
            metrics["entropy"] += entropy.item()
            metrics["approx_kl"] += approx_kl
            metrics["clip_frac"] += clip_frac
            metrics["n_updates"] += 1

    # Average
    nu = max(metrics["n_updates"], 1)
    for k in ["policy_loss", "value_loss", "entropy", "approx_kl", "clip_frac"]:
        metrics[k] /= nu

    return metrics


# ---------------------------------------------------------------------------
# Main training loop
# ---------------------------------------------------------------------------


def main():
    p = argparse.ArgumentParser(description="PPO training for actor-critic transformer")
    p.add_argument("episodes", help="JSONL episode file from transformer-rl generate")
    p.add_argument("--pretrained", help="Phase 2 decision checkpoint (.pt)")
    p.add_argument("--entity-encoder", help="Pretrained entity encoder (.pt)")
    p.add_argument("-o", "--output", default="generated/actor_critic.pt")
    p.add_argument("--log", default="generated/actor_critic.csv")

    # Architecture (must match pretrained)
    p.add_argument("--d-model", type=int, default=32)
    p.add_argument("--d-ff", type=int, default=64)
    p.add_argument("--n-layers", type=int, default=4)
    p.add_argument("--n-heads", type=int, default=4)

    # PPO hyperparams
    p.add_argument("--ppo-epochs", type=int, default=4)
    p.add_argument("--batch-size", type=int, default=256)
    p.add_argument("--lr", type=float, default=3e-4)
    p.add_argument("--weight-decay", type=float, default=1.0)
    p.add_argument("--gamma", type=float, default=0.99)
    p.add_argument("--gae-lambda", type=float, default=0.95)
    p.add_argument("--clip-eps", type=float, default=0.2)
    p.add_argument("--value-coeff", type=float, default=0.5)
    p.add_argument("--entropy-coeff", type=float, default=0.01)
    p.add_argument("--max-grad-norm", type=float, default=0.5)

    # Grokfast
    p.add_argument("--grokfast-alpha", type=float, default=0.98)
    p.add_argument("--grokfast-lamb", type=float, default=2.0)
    p.add_argument("--no-grokfast", action="store_true")

    # Freeze
    p.add_argument(
        "--freeze-transformer",
        action="store_true",
        default=True,
        help="Freeze ability transformer encoder (default: frozen)",
    )
    p.add_argument("--unfreeze-transformer", action="store_true")

    args = p.parse_args()

    tok = AbilityTokenizer()
    print(f"Device: {DEVICE}")

    # Build model
    model = AbilityActorCritic(
        vocab_size=tok.vocab_size,
        game_state_dim=210,
        d_model=args.d_model,
        d_ff=args.d_ff,
        n_layers=args.n_layers,
        n_heads=args.n_heads,
    ).to(DEVICE)

    # Load pretrained weights (partial — skip missing keys like base_head, ability_proj, value_head)
    if args.pretrained:
        print(f"Loading pretrained decision model: {args.pretrained}")
        state = torch.load(args.pretrained, map_location=DEVICE, weights_only=True)
        # Map from AbilityTransformerDecision keys to AbilityActorCritic
        missing, unexpected = model.load_state_dict(state, strict=False)
        print(f"  Loaded: {len(state) - len(unexpected)} params, missing: {len(missing)}, unexpected: {len(unexpected)}")
        if missing:
            print(f"  Missing (will be randomly initialized): {missing[:10]}...")
        if unexpected:
            print(f"  Unexpected (ignored): {unexpected[:10]}...")

    if args.entity_encoder:
        print(f"Loading entity encoder: {args.entity_encoder}")
        state = torch.load(args.entity_encoder, map_location=DEVICE, weights_only=True)
        # Map encoder keys
        enc_state = {}
        for k, v in state.items():
            if k.startswith("encoder."):
                new_key = k.replace("encoder.", "entity_encoder.", 1)
                enc_state[new_key] = v
        missing, unexpected = model.load_state_dict(enc_state, strict=False)
        loaded = len(enc_state) - len(unexpected)
        print(f"  Loaded {loaded} entity encoder params")

    # Freeze transformer if requested
    freeze_transformer = args.freeze_transformer and not args.unfreeze_transformer
    if freeze_transformer:
        for param in model.transformer.parameters():
            param.requires_grad = False
        n_frozen = sum(p.numel() for p in model.transformer.parameters())
        print(f"Froze transformer encoder ({n_frozen:,} params)")

    n_trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    n_total = sum(p.numel() for p in model.parameters())
    print(f"Model: {n_total:,} total params, {n_trainable:,} trainable")

    # Optimizer
    optimizer = torch.optim.AdamW(
        filter(lambda p: p.requires_grad, model.parameters()),
        lr=args.lr,
        betas=(0.9, 0.98),
        weight_decay=args.weight_decay,
    )

    grokfast = None
    if not args.no_grokfast:
        grokfast = GrokfastEMA(model, alpha=args.grokfast_alpha, lamb=args.grokfast_lamb)
        print(f"Grokfast EMA: alpha={args.grokfast_alpha}, lambda={args.grokfast_lamb}")

    # Load episodes
    print(f"\nLoading episodes from {args.episodes}...")
    episodes = load_episodes(Path(args.episodes))
    print(f"  {len(episodes)} episodes, {sum(len(e['steps']) for e in episodes)} total steps")

    wins = sum(1 for e in episodes if e["outcome"] == "Victory")
    print(f"  Win rate in data: {wins}/{len(episodes)} ({wins/max(len(episodes),1)*100:.1f}%)")

    # Compute GAE
    print("Computing GAE advantages...")
    advantages, returns, old_values = compute_gae(
        episodes, model.forward_value, tok,
        gamma=args.gamma, lam=args.gae_lambda,
    )
    steps_flat, ep_indices = flatten_steps(episodes)
    print(f"  Advantages: mean={advantages.mean():.4f}, std={advantages.std():.4f}")
    print(f"  Returns: mean={returns.mean():.4f}, std={returns.std():.4f}")

    # CSV logging
    log_path = Path(args.log)
    log_file = open(log_path, "w", newline="")
    writer = csv.writer(log_file)
    writer.writerow([
        "epoch", "policy_loss", "value_loss", "entropy",
        "approx_kl", "clip_frac", "elapsed_s",
    ])

    # PPO training
    t0 = time.time()
    print(f"\nStarting PPO training ({args.ppo_epochs} epochs per batch)...")

    metrics = ppo_update(
        model, optimizer, grokfast,
        steps_flat, advantages, returns, episodes, tok,
        clip_eps=args.clip_eps,
        value_coeff=args.value_coeff,
        entropy_coeff=args.entropy_coeff,
        ppo_epochs=args.ppo_epochs,
        batch_size=args.batch_size,
        max_grad_norm=args.max_grad_norm,
    )

    elapsed = time.time() - t0
    print(f"\nPPO update complete in {elapsed:.1f}s")
    print(f"  Policy loss:  {metrics['policy_loss']:.4f}")
    print(f"  Value loss:   {metrics['value_loss']:.4f}")
    print(f"  Entropy:      {metrics['entropy']:.4f}")
    print(f"  Approx KL:    {metrics['approx_kl']:.4f}")
    print(f"  Clip fraction: {metrics['clip_frac']:.3f}")

    writer.writerow([
        1, metrics["policy_loss"], metrics["value_loss"],
        metrics["entropy"], metrics["approx_kl"], metrics["clip_frac"],
        f"{elapsed:.1f}",
    ])
    log_file.flush()

    # Save checkpoint
    torch.save(model.state_dict(), args.output)
    print(f"\nSaved checkpoint to {args.output}")
    print(f"Training log: {args.log}")

    log_file.close()


if __name__ == "__main__":
    main()
