use std::collections::{HashMap, VecDeque};

use crate::ai::core::{
    run_replay, step, ReplayResult, SimState, Team, UnitIntent,
};
use super::types::*;

pub fn sample_phase2_party_state(seed: u64) -> SimState {
    let mut state = crate::ai::core::sample_duel_state(seed);
    state.units = vec![
        crate::ai::core::UnitState {
            id: 1,
            team: Team::Hero,
            hp: 145,
            max_hp: 145,
            position: crate::ai::core::sim_vec2(-2.0, -1.0),
            move_speed_per_sec: 3.8,
            attack_damage: 11,
            attack_range: 1.3,
            attack_cooldown_ms: 700,
            attack_cast_time_ms: 300,
            cooldown_remaining_ms: 0,
            ability_damage: 22,
            ability_range: 1.8,
            ability_cooldown_ms: 3_100,
            ability_cast_time_ms: 520,
            ability_cooldown_remaining_ms: 0,
            heal_amount: 0,
            heal_range: 0.0,
            heal_cooldown_ms: 0,
            heal_cast_time_ms: 0,
            heal_cooldown_remaining_ms: 0,
            control_range: 0.0,
            control_duration_ms: 0,
            control_cooldown_ms: 0,
            control_cast_time_ms: 0,
            control_cooldown_remaining_ms: 0,
            control_remaining_ms: 0,
            casting: None,
            abilities: Vec::new(),
            passives: Vec::new(),
            status_effects: Vec::new(),
            shield_hp: 0,
            resistance_tags: HashMap::new(),
            state_history: VecDeque::new(),
            channeling: None,
            resource: 0,
            max_resource: 0,
            resource_regen_per_sec: 0.0, owner_id: None, directed: false, armor: 0.0, magic_resist: 0.0, cover_bonus: 0.0, elevation: 0.0, total_healing_done: 0, total_damage_done: 0,
        },
        crate::ai::core::UnitState {
            id: 2,
            team: Team::Hero,
            hp: 98,
            max_hp: 98,
            position: crate::ai::core::sim_vec2(-4.0, 0.2),
            move_speed_per_sec: 4.7,
            attack_damage: 14,
            attack_range: 1.5,
            attack_cooldown_ms: 580,
            attack_cast_time_ms: 240,
            cooldown_remaining_ms: 0,
            ability_damage: 28,
            ability_range: 2.1,
            ability_cooldown_ms: 2_600,
            ability_cast_time_ms: 420,
            ability_cooldown_remaining_ms: 0,
            heal_amount: 0,
            heal_range: 0.0,
            heal_cooldown_ms: 0,
            heal_cast_time_ms: 0,
            heal_cooldown_remaining_ms: 0,
            control_range: 0.0,
            control_duration_ms: 0,
            control_cooldown_ms: 0,
            control_cast_time_ms: 0,
            control_cooldown_remaining_ms: 0,
            control_remaining_ms: 0,
            casting: None,
            abilities: Vec::new(),
            passives: Vec::new(),
            status_effects: Vec::new(),
            shield_hp: 0,
            resistance_tags: HashMap::new(),
            state_history: VecDeque::new(),
            channeling: None,
            resource: 0,
            max_resource: 0,
            resource_regen_per_sec: 0.0, owner_id: None, directed: false, armor: 0.0, magic_resist: 0.0, cover_bonus: 0.0, elevation: 0.0, total_healing_done: 0, total_damage_done: 0,
        },
        crate::ai::core::UnitState {
            id: 3,
            team: Team::Hero,
            hp: 92,
            max_hp: 92,
            position: crate::ai::core::sim_vec2(-5.5, 1.0),
            move_speed_per_sec: 4.2,
            attack_damage: 8,
            attack_range: 1.3,
            attack_cooldown_ms: 650,
            attack_cast_time_ms: 260,
            cooldown_remaining_ms: 0,
            ability_damage: 0,
            ability_range: 0.0,
            ability_cooldown_ms: 0,
            ability_cast_time_ms: 0,
            ability_cooldown_remaining_ms: 0,
            heal_amount: 24,
            heal_range: 2.7,
            heal_cooldown_ms: 2_200,
            heal_cast_time_ms: 420,
            heal_cooldown_remaining_ms: 0,
            control_range: 0.0,
            control_duration_ms: 0,
            control_cooldown_ms: 0,
            control_cast_time_ms: 0,
            control_cooldown_remaining_ms: 0,
            control_remaining_ms: 0,
            casting: None,
            abilities: Vec::new(),
            passives: Vec::new(),
            status_effects: Vec::new(),
            shield_hp: 0,
            resistance_tags: HashMap::new(),
            state_history: VecDeque::new(),
            channeling: None,
            resource: 0,
            max_resource: 0,
            resource_regen_per_sec: 0.0, owner_id: None, directed: false, armor: 0.0, magic_resist: 0.0, cover_bonus: 0.0, elevation: 0.0, total_healing_done: 0, total_damage_done: 0,
        },
        crate::ai::core::UnitState {
            id: 4,
            team: Team::Enemy,
            hp: 142,
            max_hp: 142,
            position: crate::ai::core::sim_vec2(8.0, -1.0),
            move_speed_per_sec: 3.7,
            attack_damage: 10,
            attack_range: 1.2,
            attack_cooldown_ms: 720,
            attack_cast_time_ms: 320,
            cooldown_remaining_ms: 0,
            ability_damage: 21,
            ability_range: 1.7,
            ability_cooldown_ms: 3_000,
            ability_cast_time_ms: 500,
            ability_cooldown_remaining_ms: 0,
            heal_amount: 0,
            heal_range: 0.0,
            heal_cooldown_ms: 0,
            heal_cast_time_ms: 0,
            heal_cooldown_remaining_ms: 0,
            control_range: 0.0,
            control_duration_ms: 0,
            control_cooldown_ms: 0,
            control_cast_time_ms: 0,
            control_cooldown_remaining_ms: 0,
            control_remaining_ms: 0,
            casting: None,
            abilities: Vec::new(),
            passives: Vec::new(),
            status_effects: Vec::new(),
            shield_hp: 0,
            resistance_tags: HashMap::new(),
            state_history: VecDeque::new(),
            channeling: None,
            resource: 0,
            max_resource: 0,
            resource_regen_per_sec: 0.0, owner_id: None, directed: false, armor: 0.0, magic_resist: 0.0, cover_bonus: 0.0, elevation: 0.0, total_healing_done: 0, total_damage_done: 0,
        },
        crate::ai::core::UnitState {
            id: 5,
            team: Team::Enemy,
            hp: 96,
            max_hp: 96,
            position: crate::ai::core::sim_vec2(10.0, 0.2),
            move_speed_per_sec: 4.8,
            attack_damage: 13,
            attack_range: 1.5,
            attack_cooldown_ms: 560,
            attack_cast_time_ms: 230,
            cooldown_remaining_ms: 0,
            ability_damage: 27,
            ability_range: 2.0,
            ability_cooldown_ms: 2_600,
            ability_cast_time_ms: 410,
            ability_cooldown_remaining_ms: 0,
            heal_amount: 0,
            heal_range: 0.0,
            heal_cooldown_ms: 0,
            heal_cast_time_ms: 0,
            heal_cooldown_remaining_ms: 0,
            control_range: 0.0,
            control_duration_ms: 0,
            control_cooldown_ms: 0,
            control_cast_time_ms: 0,
            control_cooldown_remaining_ms: 0,
            control_remaining_ms: 0,
            casting: None,
            abilities: Vec::new(),
            passives: Vec::new(),
            status_effects: Vec::new(),
            shield_hp: 0,
            resistance_tags: HashMap::new(),
            state_history: VecDeque::new(),
            channeling: None,
            resource: 0,
            max_resource: 0,
            resource_regen_per_sec: 0.0, owner_id: None, directed: false, armor: 0.0, magic_resist: 0.0, cover_bonus: 0.0, elevation: 0.0, total_healing_done: 0, total_damage_done: 0,
        },
        crate::ai::core::UnitState {
            id: 6,
            team: Team::Enemy,
            hp: 94,
            max_hp: 94,
            position: crate::ai::core::sim_vec2(11.5, 1.0),
            move_speed_per_sec: 4.1,
            attack_damage: 8,
            attack_range: 1.3,
            attack_cooldown_ms: 660,
            attack_cast_time_ms: 270,
            cooldown_remaining_ms: 0,
            ability_damage: 0,
            ability_range: 0.0,
            ability_cooldown_ms: 0,
            ability_cast_time_ms: 0,
            ability_cooldown_remaining_ms: 0,
            heal_amount: 23,
            heal_range: 2.6,
            heal_cooldown_ms: 2_200,
            heal_cast_time_ms: 430,
            heal_cooldown_remaining_ms: 0,
            control_range: 0.0,
            control_duration_ms: 0,
            control_cooldown_ms: 0,
            control_cast_time_ms: 0,
            control_cooldown_remaining_ms: 0,
            control_remaining_ms: 0,
            casting: None,
            abilities: Vec::new(),
            passives: Vec::new(),
            status_effects: Vec::new(),
            shield_hp: 0,
            resistance_tags: HashMap::new(),
            state_history: VecDeque::new(),
            channeling: None,
            resource: 0,
            max_resource: 0,
            resource_regen_per_sec: 0.0, owner_id: None, directed: false, armor: 0.0, magic_resist: 0.0, cover_bonus: 0.0, elevation: 0.0, total_healing_done: 0, total_damage_done: 0,
        },
    ];
    state.units.sort_by_key(|u| u.id);
    state
}

pub fn default_roles() -> HashMap<u32, Role> {
    HashMap::from([
        (1, Role::Tank),
        (2, Role::Dps),
        (3, Role::Healer),
        (4, Role::Tank),
        (5, Role::Dps),
        (6, Role::Healer),
    ])
}

pub fn generate_scripted_intents(
    initial: &SimState,
    ticks: u32,
    dt_ms: u32,
    roles: HashMap<u32, Role>,
) -> Vec<Vec<UnitIntent>> {
    let mut ai = RoleAiState::new(initial, roles);
    let mut state = initial.clone();
    let mut script = Vec::with_capacity(ticks as usize);

    for _ in 0..ticks {
        let intents = generate_intents(&state, &mut ai, dt_ms);
        script.push(intents.clone());
        let (new_state, events) = step(state, &intents, dt_ms);
        ai.update_from_events(&events);
        state = new_state;
    }

    script
}

pub fn run_phase2_sample(seed: u64, ticks: u32, dt_ms: u32) -> ReplayResult {
    let initial = sample_phase2_party_state(seed);
    let script = generate_scripted_intents(&initial, ticks, dt_ms, default_roles());
    run_replay(initial, &script, ticks, dt_ms)
}
