use bevy::prelude::*;

use crate::game_core;

#[derive(Component)]
pub struct OverworldTerrainVisual;

#[derive(Resource)]
pub struct HubMenuState {
    pub selected: usize,
    pub notice: String,
}

impl Default for HubMenuState {
    fn default() -> Self {
        Self {
            selected: 0,
            notice: "Welcome back, Commander. The guild is ready.".to_string(),
        }
    }
}

#[derive(Resource)]
pub struct StartMenuState {
    pub subtitle: String,
    pub status: String,
    pub hamburger_expanded: bool,
}

impl Default for StartMenuState {
    fn default() -> Self {
        Self {
            subtitle: Self::default_subtitle().to_string(),
            status: Self::default_status().to_string(),
            hamburger_expanded: true,
        }
    }
}

impl StartMenuState {
    pub fn default_subtitle() -> &'static str {
        "Begin a new campaign or continue your latest compatible save."
    }

    pub fn default_status() -> &'static str {
        "Select New Campaign to begin or Continue Campaign to resume."
    }

    pub fn reset_for_entry(&mut self) {
        self.subtitle = Self::default_subtitle().to_string();
        self.status = Self::default_status().to_string();
        self.hamburger_expanded = true;
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HubAction {
    AssembleExpedition,
    ReviewRecruits,
    IntelSweep,
    DispatchRelief,
    LeaveGuild,
}

impl HubAction {
    pub fn from_selected(selected: usize) -> Self {
        match selected {
            0 => Self::AssembleExpedition,
            1 => Self::ReviewRecruits,
            2 => Self::IntelSweep,
            3 => Self::DispatchRelief,
            _ => Self::LeaveGuild,
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            Self::AssembleExpedition => "Assemble Expedition",
            Self::ReviewRecruits => "Review Recruits",
            Self::IntelSweep => "Intel Sweep",
            Self::DispatchRelief => "Dispatch Relief",
            Self::LeaveGuild => "Leave Guild",
        }
    }
}

#[derive(Resource, Default)]
pub struct HubActionQueue {
    pub pending: Option<HubAction>,
    pub actions_taken: u32,
}

#[derive(Resource, Clone)]
pub struct CharacterCreationUiState {
    pub status: String,
}

impl Default for CharacterCreationUiState {
    fn default() -> Self {
        Self {
            status: "Select a faction to continue to backstory.".to_string(),
        }
    }
}

/// Tracks whether a campaign outcome has been detected and shown to the player.
#[derive(Resource, Default)]
pub struct CampaignOutcomeState {
    pub outcome: Option<game_core::CampaignOutcome>,
    pub shown: bool,
}

/// Persistent UI state for the hero detail panel shown in GuildManagement.
#[derive(Resource, Default)]
pub struct HeroDetailUiState {
    /// The hero id currently selected in the detail panel.  `None` = first hero.
    pub selected_hero_id: Option<u32>,
    /// A loot item generated by "Generate Test Item" that is waiting to be equipped.
    pub pending_loot: Option<game_core::EquipmentItem>,
    /// Tracks an internal seed counter so repeated button presses yield different items.
    pub loot_seed_counter: u64,
}
